apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: $APP_NAME
  name: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  strategy: { }
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - image: ghcr.io/elliotwms/pinbot:$APP_VERSION
          name: $APP_NAME
          resources: { }
          env:
            - name: APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME
                  key: APPLICATION_ID
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: $APP_NAME
                  key: TOKEN
            - name: HEALTH_CHECK_ADDR
              value: ":8080"
            - name: EXCLUDED_CHANNELS
              value: "570951589242732554"
---
apiVersion: v1
data:
  APPLICATION_ID: $PINBOT_APPLICATION_ID
  TOKEN: $PINBOT_TOKEN
kind: Secret
metadata:
  name: $APP_NAME
