name: Deploy
on:
  release:
    types: [ published ]
jobs:
  deploy-to-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    environment: Test
    env:
      APP_NAME: ${{ vars.PINBOT_APPLICATION_NAME }}
      APP_VERSION: ${{ github.ref_name }}
      PINBOT_APPLICATION_ID: ${{ secrets.PINBOT_APPLICATION_ID }}
      PINBOT_TOKEN: ${{ secrets.PINBOT_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Update deployment file
      run: envsubst < $GITHUB_WORKSPACE/.github/workflows/deploy/pinbot-deployment.yml >> $GITHUB_WORKSPACE/deployment.yml
    - name: Verify deployment
      run: cat $GITHUB_WORKSPACE/deployment.yml
